package com.examples.wsdl.helloservice_wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-11-18T19:36:25.778+05:30
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "classpath:META-INF/sample/HelloService.wsdl", name = "Hello_PortType")
@SOAPBinding(use = SOAPBinding.Use.ENCODED, parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HelloPortType {

    @WebMethod(action = "sayHello")
    @WebResult(name = "greeting", targetNamespace = "", partName = "greeting")
    public java.lang.String sayHello(
        @WebParam(partName = "firstName", name = "firstName", targetNamespace = "")
        java.lang.String firstName
    );
}
