package org.example.ui;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-11-18T21:37:21.103+05:30
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://www.example.org/ui/", name = "ui")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Ui {

    @WebMethod(operationName = "NewOperation", action = "http://www.example.org/ui/NewOperation")
    public void newOperation(
        @WebParam(partName = "parameters", mode = WebParam.Mode.INOUT, name = "parameters", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> parameters
    );
}
