package org.example.ui;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-11-18T21:37:21.163+05:30
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "ui", 
                  wsdlLocation = "file:/D:/WORK/CAMEL_TEST1/sample-home/sample-datamodel/target/../src/main/resources/sample/ui.wsdl",
                  targetNamespace = "http://www.example.org/ui/") 
public class Ui_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/ui/", "ui");
    public final static QName UiSOAP = new QName("http://www.example.org/ui/", "uiSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/WORK/CAMEL_TEST1/sample-home/sample-datamodel/target/../src/main/resources/sample/ui.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Ui_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/WORK/CAMEL_TEST1/sample-home/sample-datamodel/target/../src/main/resources/sample/ui.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Ui_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Ui_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Ui_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Ui_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Ui_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Ui_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Ui
     */
    @WebEndpoint(name = "uiSOAP")
    public Ui getUiSOAP() {
        return super.getPort(UiSOAP, Ui.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ui
     */
    @WebEndpoint(name = "uiSOAP")
    public Ui getUiSOAP(WebServiceFeature... features) {
        return super.getPort(UiSOAP, Ui.class, features);
    }

}
