package com.widgetvendor.widgetorderform;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-11-18T14:23:05.476+05:30
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "Hello_Service", 
                  wsdlLocation = "file:/D:/WORK/CAMEL_TEST1/sample-home/sample-datamodel/target/../src/main/resources/sample/sample.wsdl",
                  targetNamespace = "http://widgetVendor.com/widgetOrderForm") 
public class HelloService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://widgetVendor.com/widgetOrderForm", "Hello_Service");
    public final static QName HelloPort = new QName("http://widgetVendor.com/widgetOrderForm", "Hello_Port");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/WORK/CAMEL_TEST1/sample-home/sample-datamodel/target/../src/main/resources/sample/sample.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/WORK/CAMEL_TEST1/sample-home/sample-datamodel/target/../src/main/resources/sample/sample.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HelloService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns OrderWidgets
     */
    @WebEndpoint(name = "Hello_Port")
    public OrderWidgets getHelloPort() {
        return super.getPort(HelloPort, OrderWidgets.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderWidgets
     */
    @WebEndpoint(name = "Hello_Port")
    public OrderWidgets getHelloPort(WebServiceFeature... features) {
        return super.getPort(HelloPort, OrderWidgets.class, features);
    }

}
