package com.widgetvendor.widgetorderform;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-11-18T14:23:05.446+05:30
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://widgetVendor.com/widgetOrderForm", name = "orderWidgets")
@XmlSeeAlso({com.widgetvendor.types.widgettypes.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public class OrderWidgets {

    @WebMethod
    @WebResult(name = "price", targetNamespace = "", partName = "price")
    public float placeWidgetOrder(
        @WebParam(partName = "numOrdered", name = "numOrdered", targetNamespace = "")
        int numOrdered,
        @WebParam(partName = "keyVal", mode = WebParam.Mode.INOUT, name = "keyElem", targetNamespace = "http://widgetVendor.com/types/widgetTypes", header = true)
        javax.xml.ws.Holder<byte[]> keyVal
    ) throws BadSize{
    	System.out.println("its working..");
    	return 0;
    }
}
